name: Upload package

on:
  workflow_dispatch:
  release:
    types: ['released']

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version: ['29.1']

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Create Eldev package
      run: |
        ./bin/eldev -p -dtQTC package
      env:
        ELDEV_LOCAL: '.'

    - name: Upload it to the release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        tag: ${{github.ref}}
        file: dist/*
        file_glob: true
        overwrite: true
